name: Test Code

on:
  push:
    branches:
      - main
  pull_request:

env:
  node_version: 14

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
      - name: lint
        run: |
          npm ci
          npm run lint
